//! Router context for external calls mocks.

use std::{
    borrow::BorrowMut,
    sync::{Arc, Mutex, TryLockError},
    thread::ThreadId,
};

use alloy_primitives::{uint, Address};
use dashmap::{mapref::one::RefMut, DashMap};
use once_cell::sync::Lazy;
use stylus_sdk::{
    abi::Router,
    prelude::{StorageType, TopLevelStorage},
    ArbResult,
};

use crate::storage_access::AccessStorage;

/// Router Storage.
///
/// A global mutable key-value store that allows concurrent access.
///
/// The key is the [`RouterContext`], a combination of [`ThreadId`] and
/// [`Address`] to avoid a panic on lock, while calling more than two contracts
/// consecutive.
///
/// The value is the [`RouterStorage`], a router of the contract generated by
/// `stylus-sdk`.
///
/// NOTE: The [`RouterContext::storage`] will panic on lock, when the same key
/// is accessed twice from the same thread.
static ROUTER_STORAGE: Lazy<DashMap<RouterContext, RouterStorage>> =
    Lazy::new(DashMap::new);

/// Context for the router of a test contract for current test thread and
/// contract's address.
#[derive(Hash, Eq, PartialEq, Copy, Clone)]
pub(crate) struct RouterContext {
    thread_id: ThreadId,
    contract_address: Address,
}

impl RouterContext {
    /// Create a new router context.
    pub(crate) fn new(thread: ThreadId, contract_address: Address) -> Self {
        Self { thread_id: thread, contract_address }
    }

    /// Get reference to the call storage for the current test thread.
    fn storage(self) -> RefMut<'static, RouterContext, RouterStorage> {
        ROUTER_STORAGE.access_storage(&self)
    }

    /// Check if the router exists for the contract.
    pub(crate) fn exists(self) -> bool {
        ROUTER_STORAGE.contains_key(&self)
    }

    pub(crate) fn route(
        self,
        selector: u32,
        input: &[u8],
    ) -> Option<ArbResult> {
        let storage = self.storage();
        let router = Arc::clone(&storage.router);

        // Drop the storage reference to avoid a panic on lock.
        drop(storage);

        // Try to get lock on the router.
        let lock_result = router.try_lock();
        match lock_result {
            // If lock is acquired, route the message.
            Ok(mut router) => router.route(selector, input),
            // Panic instead of locking.
            Err(TryLockError::WouldBlock) => {
                panic!("recursive calls are not supported in motsu")
            }
            // This branch should not be reached, since we don't catch
            // panics.
            Err(TryLockError::Poisoned(_)) => {
                panic!("should not call contract that panicked")
            }
        }
    }

    /// Initialise contract router for the current test thread and
    /// `contract_address`.
    pub(crate) fn init_storage<ST: StorageType + TestRouter + 'static>(self) {
        let contract_address = self.contract_address;
        if ROUTER_STORAGE
            .insert(
                self,
                RouterStorage {
                    router: Arc::new(Mutex::new(unsafe {
                        ST::new(uint!(0_U256), 0)
                    })),
                },
            )
            .is_some()
        {
            panic!("contract's router is already initialized - contract_address is {contract_address}");
        }
    }

    /// Reset router storage for the current [`RouterContext`].
    pub(crate) fn reset_storage(self) {
        ROUTER_STORAGE.remove(&self);
    }
}

/// Metadata related to the router of an external contract.
struct RouterStorage {
    // Contract's router.
    // NOTE: Mutex is important since contract type is not `Sync`.
    router: Arc<Mutex<dyn TestRouter>>,
}

/// A trait for routing messages to the appropriate selector in tests.
#[allow(clippy::module_name_repetitions)]
pub trait TestRouter: Send {
    /// Tries to find and execute a method for the given `selector`, returning
    /// `None` if the `selector` wasn't found.
    fn route(&mut self, selector: u32, input: &[u8]) -> Option<ArbResult>;
}

impl<R> TestRouter for R
where
    R: Router<R> + TopLevelStorage + BorrowMut<R::Storage> + Send,
{
    fn route(&mut self, selector: u32, input: &[u8]) -> Option<ArbResult> {
        <Self as Router<R>>::route(self, selector, input)
    }
}
